### ISSUE TITLE
help with improving search capabilities

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/GWASCatalogSearchDB#3]
Hi,
  I just realized that I was building the search corpus incorrectly.  I wonder if it would be easy to include in the DISEASE.TRAIT column from gwascatalog_metadata in the efo_labels data frame.  I am currently building the search terms based on the Object column of that DB, but that is not the disease traits from the study, but rather the text descriptions from the ontology.
  Also, if you know how we could also obtain the list of synonyms for EFO terms I would like to start to consider how to use those in building the text corpus.
  thanks
    Robert

**Comment by rgentlem** [comment]
Oops - that won't work, I need to search the DISEASE.TRAIT column separately - since multiple disease traits can map to an EFO term...and then link that back to the EFO table.

**Comment by rsgoncalves** [comment]
Hi Robert, to follow up on these couple of points:

- Regarding improved search support: in the latest (v0.4.0) release, the `gwascatalog_mappings` table should help a bit since it stores one mapping per row, making the original mappings in the metadata more usable.

- A Synonyms table is now included: `efo_synonyms` which has EFO terms (`Subject` column) and their (potentially multiple) synonyms (in `Object` column).
